### ISSUE TITLE
bokeh-2.4.0 (server) fails to render ipywidgets

### ISSUE THREAD

**Issue by epifanio** [bokeh/ipywidgets_bokeh#35]
Trying to run the [ipyleaflet_tiles.py](https://github.com/bokeh/bokeh/blob/branch-3.0/examples/howto/ipywidgets/ipyleaflet_tiles.py) I got the following error:

```
  File "/home/epinux/.local/lib/python3.9/site-packages/ipywidgets_bokeh/kernel.py", line 67, in send
    self._trigger_change(event)
  File "/home/epinux/.local/lib/python3.9/site-packages/ipywidgets_bokeh/kernel.py", line 83, in _trigger_change
    self.document._trigger_on_change(event)
AttributeError: 'Document' object has no attribute '_trigger_on_change'
```

full log: https://gist.github.com/epifanio/7f930b959684fe71f73c75bc65488f1c

The same code works running bokeh 2.3.2, I tried to upgrade [ipywidgets, ipywidgets_bokeh] to the latest releases, but the error persists.

**Comment by epifanio** [comment]
Not sure if this is still related to the same issue,  but attempting to run and bokeh server app I got the following log after upgrading to pip installed bokeh+ipywidgets_bokeh

```
metsis_bokeh.1.ui3kg52oezom@epinux.com    | Traceback (most recent call last):
metsis_bokeh.1.ui3kg52oezom@epinux.com    |   File "/opt/venv/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
metsis_bokeh.1.ui3kg52oezom@epinux.com    |     result = await result
metsis_bokeh.1.ui3kg52oezom@epinux.com    |   File "/opt/venv/lib/python3.9/site-packages/bokeh/server/views/doc_handler.py", line 56, in get
metsis_bokeh.1.ui3kg52oezom@epinux.com    |     page = server_html_page_for_session(session,
metsis_bokeh.1.ui3kg52oezom@epinux.com    |   File "/opt/venv/lib/python3.9/site-packages/bokeh/embed/server.py", line 255, in server_html_page_for_session
metsis_bokeh.1.ui3kg52oezom@epinux.com    |     bundle = bundle_for_objs_and_resources(None, resources)
metsis_bokeh.1.ui3kg52oezom@epinux.com    |   File "/opt/venv/lib/python3.9/site-packages/bokeh/embed/bundle.py", line 220, in bundle_for_objs_and_resources
metsis_bokeh.1.ui3kg52oezom@epinux.com    |     extensions = _bundle_extensions(objs, js_resources)
metsis_bokeh.1.ui3kg52oezom@epinux.com    |   File "/opt/venv/lib/python3.9/site-packages/bokeh/embed/bundle.py", line 348, in _bundle_extensions
metsis_bokeh.1.ui3kg52oezom@epinux.com    |     raise ValueError(f"can't resolve artifact path for '{name}' extension")
metsis_bokeh.1.ui3kg52oezom@epinux.com    | ValueError: can't resolve artifact path for 'ipywidgets_bokeh' extension
```

The log is from a docker container running a bokeh server application.
Log into tat container returns the following versions:

```
ipywidgets_bokeh.__version__
'1.2.0'

bokeh.__version___
'2.4.0'

ipywidgets.__version__
'7.6.5'

ipykernel.__version__
'6.4.1'
```

**Comment by philippjfr** [comment]
@epifanio Where did you install it from pip or conda?

**Comment by philippjfr** [comment]
Sounds like this was `pip` and I just double checked that the `dist` dir exists. Will have to investigate.

**Comment by philippjfr** [comment]
Okay, found the culprit, the package.json is missing in the package. Will submit a fix.
