### ISSUE TITLE
Support for bokeh >= 3.0.0

### ISSUE THREAD

**Issue by SergioLoaiza** [bokeh/ipywidgets_bokeh#67]
Hi; any plan for updating the library in order to support bokeh >= 3.0.0?

**Comment by raybellwaves** [comment]
```
pip install "bokeh>=3.0.0" ipywidgets-bokeh
python
import ipywidgets_bokeh
```

gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/ipywidgets_bokeh/__init__.py", line 1, in <module>
    from .widget import IPyWidget
  File "/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/ipywidgets_bokeh/widget.py", line 9, in <module>
    from bokeh.models.layouts import HTMLBox
ImportError: cannot import name 'HTMLBox' from 'bokeh.models.layouts' (/Users/ray/miniforge3/envs/test_env/lib/python3.10/site-packages/bokeh/models/layouts.py)
```

**Comment by ndmlny-qs** [comment]
I have an update @SergioLoaiza and @raybellwaves. @mattpap started the branch #51 for updating to Bokeh 3.0, and I am assigning this issue to myself to get the needed changes made. I'll use this issue to link to the PR, so stay tuned.
